# Generated by Django 4.1 on 2025-04-08 16:00

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True,
                default=bson.objectid.ObjectId,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
